import bpy
skeleton = bpy.context.object.data.expykit_retarget

skeleton.face.left_eye = 'LeftEye'
skeleton.face.right_eye = 'RightEye'
skeleton.face.jaw = 'Jaw'
skeleton.spine.head = 'Head'
skeleton.spine.neck = 'Neck'
skeleton.spine.spine2 = 'Spine2'
skeleton.spine.spine1 = 'Spine1'
skeleton.spine.spine = 'Spine'
skeleton.spine.hips = 'Hips'
skeleton.right_arm.shoulder = 'RightShoulder'
skeleton.right_arm.arm = 'RightArm'
skeleton.right_arm.arm_twist = ''
skeleton.right_arm.forearm = 'RightForeArm'
skeleton.right_arm.forearm_twist = ''
skeleton.right_arm.hand = 'RightHand'
skeleton.left_arm.shoulder = 'LeftShoulder'
skeleton.left_arm.arm = 'LeftArm'
skeleton.left_arm.arm_twist = ''
skeleton.left_arm.forearm = 'LeftForeArm'
skeleton.left_arm.forearm_twist = ''
skeleton.left_arm.hand = 'LeftHand'
skeleton.right_leg.upleg = 'RightUpLeg'
skeleton.right_leg.upleg_twist = ''
skeleton.right_leg.leg = 'RightLeg'
skeleton.right_leg.leg_twist = ''
skeleton.right_leg.foot = 'RightFoot'
skeleton.right_leg.toe = 'RightToeBase'
skeleton.left_leg.upleg = 'LeftUpLeg'
skeleton.left_leg.upleg_twist = ''
skeleton.left_leg.leg = 'LeftLeg'
skeleton.left_leg.leg_twist = ''
skeleton.left_leg.foot = 'LeftFoot'
skeleton.left_leg.toe = 'LeftToeBase'

skeleton.left_fingers.thumb.a = 'LeftHandThumb1'
skeleton.left_fingers.thumb.b = 'LeftHandThumb2'
skeleton.left_fingers.thumb.c = 'LeftHandThumb3'

skeleton.left_fingers.index.a = 'LeftHandIndex1'
skeleton.left_fingers.index.b = 'LeftHandIndex2'
skeleton.left_fingers.index.c = 'LeftHandIndex3'

skeleton.left_fingers.middle.a = 'LeftHandMiddle1'
skeleton.left_fingers.middle.b = 'LeftHandMiddle2'
skeleton.left_fingers.middle.c = 'LeftHandMiddle3'

skeleton.left_fingers.ring.a = 'LeftHandRing1'
skeleton.left_fingers.ring.b = 'LeftHandRing2'
skeleton.left_fingers.ring.c = 'LeftHandRing3'

skeleton.left_fingers.pinky.a = 'LeftHandPinky1'
skeleton.left_fingers.pinky.b = 'LeftHandPinky2'
skeleton.left_fingers.pinky.c = 'LeftHandPinky3'

skeleton.right_fingers.thumb.a = 'RightHandThumb1'
skeleton.right_fingers.thumb.b = 'RightHandThumb2'
skeleton.right_fingers.thumb.c = 'RightHandThumb3'

skeleton.right_fingers.index.a = 'RightHandIndex1'
skeleton.right_fingers.index.b = 'RightHandIndex2'
skeleton.right_fingers.index.c = 'RightHandIndex3'

skeleton.right_fingers.middle.a = 'RightHandMiddle1'
skeleton.right_fingers.middle.b = 'RightHandMiddle2'
skeleton.right_fingers.middle.c = 'RightHandMiddle3'

skeleton.right_fingers.ring.a = 'RightHandRing1'
skeleton.right_fingers.ring.b = 'RightHandRing2'
skeleton.right_fingers.ring.c = 'RightHandRing3'

skeleton.right_fingers.pinky.a = 'RightHandPinky1'
skeleton.right_fingers.pinky.b = 'RightHandPinky2'
skeleton.right_fingers.pinky.c = 'RightHandPinky3'